baseURL = "http://getgianmarco.com"
languageCode = "en-us"
title = "Gianmarco Picarella"
theme = []

[params]
  author = "Gianmarco Picarella"
  subtitle = "Software Engineer at Google; Developer of Mario+Rabbids: Sparks of Hope; MS in Computer Science; Based in Warsaw, PL; From Anzio, IT."
  github = "https://github.com/gianmarcopicarella"
  linkedin = "https://www.linkedin.com/in/gianmarcopicarella/"
  cv = "http://getgianmarco.com/picarella_gianmarco_cv.pdf"
  blog = "https://gianmarcopicarella.substack.com/"
